# General docker-compose configuration

version: "3.9"

services:

  mongo:
    image: mongo:4.4.6
    restart: unless-stopped
    ports:
      - 27017:27017
    networks:
      - devnetwork

  redis:
    image: redis:6.2.3
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - devnetwork

  backend:
    image: backend-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
    ports:
      - 8080:8080
    volumes:
      - /home/app/node_modules
      - ./backend:/home/app
    networks:
      - devnetwork

  frontend:
    image: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - 3000:3000
    volumes:
      - /home/app/node_modules
      - ./frontend:/home/app
    networks:
      - devnetwork

networks:
  devnetwork: