# General docker-compose configuration

version: "3.9"

services:

  mongo:
    image: mongo:4.4.6
    restart: unless-stopped
    expose:
      - "27017"
    networks:
      - devnetwork

  redis:
    image: redis:6.2.6-alpine
    restart: unless-stopped
    expose:
      - "6379"
    # Persistent data volume might be worth to consider
    # Not really needed for current use cases and produces more load on server
    networks:
      - devnetwork

  backend:
    image: backend-api
    restart: unless-stopped
    depends_on:
      - mongo
      - redis
    expose:
      - "8080"
    networks:
      - devnetwork

networks:
  devnetwork: