# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Full Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ development, main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node-version: [14.x, 15.x]
        mongodb-version: [4.2]

    steps:
    - name: Git checkout 
      uses: actions/checkout@v2
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    
    - run: npm ci
    - run: npm run install:back
    - run: npm run install:front
    - run: npm run test:full-cov

    - name: Coverage Reporting
      uses: codecov/codecov-action@v1
      if: ${{ always() }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
      
    env:
      SECRET: ${{ secrets.SECRET }}
      MONGO_PORT: ${{ secrets.MONGO_PORT }}
      MONGO_URL: ${{ secrets.MONGO_URL }}
      MONGO_TEST_DB: ${{ secrets.MONGO_TEST_DB }}
